import { test, expect } from '@playwright/test'

test('文件页 detach 支持文件夹卡和面包屑目录目标', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '文件系统' }).click()
  await page.getByRole('button', { name: 'detach' }).last().click()

  const file = page.locator('.file-item[data-file-id="file:readme"]')
  const fileTarget = page.locator('.file-item.folder[data-file-id="folder:references"]')
  const fileBox = await file.boundingBox()
  const fileTargetBox = await fileTarget.boundingBox()
  if (!fileBox || !fileTargetBox) throw new Error('文件或目标文件夹未渲染')
  await page.mouse.move(fileBox.x + fileBox.width / 2, fileBox.y + fileBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(fileTargetBox.x + fileTargetBox.width / 2, fileTargetBox.y + fileTargetBox.height / 2, { steps: 12 })
  await page.mouse.up()
  await expect(page.locator('[data-runtime-proxy="true"]')).toHaveCount(0)

  // 文件完成吸收后，原目标文件夹仍必须保留 Runtime 的 pointerdown 入口。
  const targetFolderAfterFileDrop = page.locator('.file-item.folder[data-file-id="folder:references"]')
  const targetAfterFileDropBox = await targetFolderAfterFileDrop.boundingBox()
  if (!targetAfterFileDropBox) throw new Error('文件夹目标在文件落地后消失')
  await page.mouse.move(targetAfterFileDropBox.x + targetAfterFileDropBox.width / 2, targetAfterFileDropBox.y + targetAfterFileDropBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(targetAfterFileDropBox.x + targetAfterFileDropBox.width / 2 + 28, targetAfterFileDropBox.y + targetAfterFileDropBox.height / 2 + 8, { steps: 5 })
  await expect(page.locator('[data-runtime-proxy="true"]')).toHaveCount(1)
  await page.mouse.up()
  await expect(page.locator('[data-runtime-proxy="true"]')).toHaveCount(0)

  const source = page.locator('.file-item.folder[data-file-id="folder:plans"]')
  const target = page.locator('.folder-sidebar button[data-file-id="folder:assets"]')
  const sourceBox = await source.boundingBox()
  if (!sourceBox) throw new Error('文件夹卡片未渲染')
  await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2)
  await page.mouse.down()
  const targetBox = await target.boundingBox()
  if (!targetBox) throw new Error('目标文件夹未渲染')
  await page.mouse.move(targetBox.x + targetBox.width / 2, targetBox.y + targetBox.height / 2, { steps: 12 })
  await page.mouse.up()
  await expect(page.locator('[data-runtime-proxy="true"]')).toHaveCount(0)
  await target.click()
  await expect(page.locator('.file-item[data-file-id^="folder:plans"]')).toHaveCount(1)

  await page.locator('.breadcrumbs button').filter({ hasText: '个人文件' }).click()
  const rootFile = page.locator('.file-item[data-file-id="file:roadmap"]')
  const rootFileBox = await rootFile.boundingBox()
  const root = page.locator('.breadcrumbs button').filter({ hasText: '个人文件' })
  const rootBox = await root.boundingBox()
  if (!rootFileBox || !rootBox) throw new Error('文件或面包屑未渲染')
  await page.mouse.move(rootFileBox.x + rootFileBox.width / 2, rootFileBox.y + rootFileBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(rootBox.x + rootBox.width / 2, rootBox.y + rootBox.height / 2, { steps: 12 })
  await page.mouse.up()
  await expect(page.locator('[data-runtime-proxy="true"]')).toHaveCount(0)
})
